import type { Asset, GenerationJob, Project, StylePreset, Variation, Review } from './types';

export const mockProjects: Project[] = [
  {
    id: 'proj-1',
    name: '春の新スタイル提案',
    salon_id: 'salon-1',
    created_at: '2024-03-01T10:00:00Z',
    updated_at: '2024-03-15T14:30:00Z',
    status: 'active',
  },
  {
    id: 'proj-2',
    name: 'カラーバリエーション比較',
    salon_id: 'salon-1',
    created_at: '2024-02-15T09:00:00Z',
    updated_at: '2024-02-28T16:00:00Z',
    status: 'active',
  },
  {
    id: 'proj-3',
    name: '過去の提案アーカイブ',
    salon_id: 'salon-1',
    created_at: '2024-01-10T11:00:00Z',
    updated_at: '2024-01-25T13:00:00Z',
    status: 'archived',
  },
];

export const mockAssets: Asset[] = [
  {
    id: 'asset-1',
    project_id: 'proj-1',
    original_url: 'https://placehold.co/800x1000/e3b7ff/FFF?text=Original+Photo+1',
    status: 'ready_for_generation',
    uploaded_by: 'user-1',
    uploaded_at: '2024-03-15T10:00:00Z',
    description: '顧客Aさんの現在のスタイル',
  },
  {
    id: 'asset-2',
    project_id: 'proj-1',
    original_url: 'https://placehold.co/800x1000/ffb7c5/FFF?text=Original+Photo+2',
    status: 'ready_for_generation',
    uploaded_by: 'user-2',
    uploaded_at: '2024-03-15T11:00:00Z',
    description: '顧客Bさんの参考画像',
  },
  {
    id: 'asset-3',
    project_id: 'proj-2',
    original_url: 'https://placehold.co/800x1000/b7e3ff/FFF?text=Original+Photo+3',
    status: 'uploaded',
    uploaded_by: 'user-1',
    uploaded_at: '2024-02-20T09:00:00Z',
  },
];

export const mockStylePresets: StylePreset[] = [
  {
    id: 'preset-1',
    name: 'ナチュラルミディアム',
    hair_length: 'ミディアム',
    color: 'ブラウン系',
    bangs: '流し前髪',
    texture: 'ふんわり',
    image_style: 'ナチュラル',
    identity_shift: 'soft_change',
    makeup_style: 'natural',
    retouch_level: 'light',
    is_custom: false,
  },
  {
    id: 'preset-2',
    name: 'モードショート',
    hair_length: 'ショート',
    color: 'アッシュ系',
    bangs: 'センターパート',
    texture: 'シャープ',
    image_style: 'モード',
    identity_shift: 'distinct_new',
    makeup_style: 'glam',
    retouch_level: 'full',
    is_custom: false,
  },
  {
    id: 'preset-3',
    name: 'フェミニンロング',
    hair_length: 'ロング',
    color: 'ピンク系',
    bangs: 'ぱっつん前髪',
    texture: 'ゆるふわ',
    image_style: 'キュート',
    identity_shift: 'distinct_new',
    makeup_style: 'glam',
    retouch_level: 'light',
    is_custom: false,
  },
  {
    id: 'preset-4',
    name: 'クールボブ',
    hair_length: 'ボブ',
    color: 'ブラック系',
    bangs: '前髪なし',
    texture: 'ストレート',
    image_style: 'クール',
    identity_shift: 'keep_similar',
    makeup_style: 'bare',
    retouch_level: 'none',
    is_custom: false,
  },
];

export const mockGenerationJobs: GenerationJob[] = [
  {
    id: 'job-1',
    asset_id: 'asset-1',
    project_id: 'proj-1',
    parameters: {
      hair_length: 'ミディアム',
      color: 'ブラウン系',
      bangs: '流し前髪',
      texture: 'ふんわり',
      image_style: 'ナチュラル',
      identity_shift: 'soft_change',
      makeup_style: 'natural',
      retouch_level: 'light',
    },
    status: 'completed',
    variation_count: 4,
    created_by: 'user-1',
    created_at: '2024-03-15T10:30:00Z',
    started_at: '2024-03-15T10:30:05Z',
    completed_at: '2024-03-15T10:31:30Z',
    response_id: 'gemini-resp-abc123',
  },
  {
    id: 'job-2',
    asset_id: 'asset-1',
    project_id: 'proj-1',
    parameters: {
      hair_length: 'ショート',
      color: 'アッシュ系',
      bangs: 'センターパート',
      texture: 'シャープ',
      image_style: 'モード',
      identity_shift: 'distinct_new',
      makeup_style: 'glam',
      retouch_level: 'full',
    },
    status: 'completed',
    variation_count: 3,
    created_by: 'user-1',
    created_at: '2024-03-15T11:00:00Z',
    started_at: '2024-03-15T11:00:05Z',
    completed_at: '2024-03-15T11:01:20Z',
    response_id: 'gemini-resp-def456',
  },
];

export const mockVariations: Variation[] = [
  {
    id: 'var-1',
    generation_job_id: 'job-1',
    variation_rank: 1,
    image_url: 'https://placehold.co/800x1000/d4a5ff/FFF?text=Variation+1-1',
    status: 'approved',
    created_at: '2024-03-15T10:31:30Z',
  },
  {
    id: 'var-2',
    generation_job_id: 'job-1',
    variation_rank: 2,
    image_url: 'https://placehold.co/800x1000/c5a5ff/FFF?text=Variation+1-2',
    status: 'reviewing',
    created_at: '2024-03-15T10:31:30Z',
  },
  {
    id: 'var-3',
    generation_job_id: 'job-1',
    variation_rank: 3,
    image_url: 'https://placehold.co/800x1000/b5a5ff/FFF?text=Variation+1-3',
    status: 'rejected',
    created_at: '2024-03-15T10:31:30Z',
  },
  {
    id: 'var-4',
    generation_job_id: 'job-1',
    variation_rank: 4,
    image_url: 'https://placehold.co/800x1000/a5a5ff/FFF?text=Variation+1-4',
    status: 'draft',
    created_at: '2024-03-15T10:31:30Z',
  },
  {
    id: 'var-5',
    generation_job_id: 'job-2',
    variation_rank: 1,
    image_url: 'https://placehold.co/800x1000/ffa5c5/FFF?text=Variation+2-1',
    status: 'approved',
    created_at: '2024-03-15T11:01:20Z',
  },
  {
    id: 'var-6',
    generation_job_id: 'job-2',
    variation_rank: 2,
    image_url: 'https://placehold.co/800x1000/ffa5d5/FFF?text=Variation+2-2',
    status: 'approved',
    created_at: '2024-03-15T11:01:20Z',
  },
  {
    id: 'var-7',
    generation_job_id: 'job-2',
    variation_rank: 3,
    image_url: 'https://placehold.co/800x1000/ffa5e5/FFF?text=Variation+2-3',
    status: 'reviewing',
    created_at: '2024-03-15T11:01:20Z',
  },
];

export const mockReviews: Review[] = [
  {
    id: 'review-1',
    variation_id: 'var-1',
    reviewed_by: 'user-1',
    status: 'approved',
    comment: 'お客様のイメージにぴったりです！',
    reviewed_at: '2024-03-15T10:35:00Z',
  },
  {
    id: 'review-2',
    variation_id: 'var-3',
    reviewed_by: 'user-1',
    status: 'rejected',
    comment: '少し暗すぎるかもしれません',
    reviewed_at: '2024-03-15T10:36:00Z',
  },
  {
    id: 'review-3',
    variation_id: 'var-5',
    reviewed_by: 'user-1',
    status: 'approved',
    comment: 'モードな雰囲気が良い',
    reviewed_at: '2024-03-15T11:05:00Z',
  },
  {
    id: 'review-4',
    variation_id: 'var-6',
    reviewed_by: 'user-2',
    status: 'approved',
    comment: 'こちらもおすすめできます',
    reviewed_at: '2024-03-15T11:06:00Z',
  },
];
